<script lang="ts" context="module">
// from carbon-design-system/sveld 
// @ https://github.com/carbon-design-system/sveld/blob/78d3a7950c6f15fbf01d824153668bde44c6f34b/src/ComponentParser.ts

interface ComponentProp {
  name: string;
  kind: "let" | "const" | "function";
  constant: boolean;
  type?: string;
  value?: unknown;
  description?: string;
  isFunction: boolean;
  isFunctionDeclaration: boolean;
  isRequired: boolean;
  reactive: boolean;
}

interface ComponentSlot {
  name?: string;
  default: boolean;
  fallback?: string;
  slot_props?: string;
  description?: string;
}

interface ForwardedEvent {
  type: "forwarded";
  name: string;
  element: ComponentInlineElement | ComponentElement;
}

interface DispatchedEvent {
  type: "dispatched";
  name: string;
  detail?: unknown;
  description?: string;
}

type ComponentEvent = ForwardedEvent | DispatchedEvent;


interface TypeDef {
  type: string;
  name: string;
  description?: string;
  ts: string;
}

interface ComponentInlineElement {
  type: "InlineComponent";
  name: string;
}

interface ComponentElement {
  type: "Element";
  name: string;
}

type RestProps = undefined | ComponentInlineElement | ComponentElement;

interface Extends {
  interface: string;
  import: string;
}

export interface ParsedComponent {
  props: ComponentProp[];
  moduleExports: ComponentProp[];
  slots: ComponentSlot[];
  events: ComponentEvent[];
  typedefs: TypeDef[];
  rest_props: RestProps;
  extends?: Extends;
  componentComment?: string;
  moduleName: string;
  filePath: string;
}
</script>
<script lang="ts">
	import CodeBlock from '$lib/Text/CodeBlock.svelte';
	import { ContentContainer, Header, Scaffold, Table, TableCell, TableHeader, TableRow }from '$lib';	
	import Link from '$lib/Text/Link.svelte';
	import type { PageData } from './$types';
	import { onMount } from 'svelte';
	import BackToTop from '$lib/Navigation/BackToTop.svelte';
	export let data: PageData;
	let componentData:ParsedComponent = data.componentData
	let iframe:HTMLIFrameElement;


	onMount(()=>{
		resizeIFrameToFitContent(iframe)
	})
	
	function resizeIFrameToFitContent( iFrame:HTMLIFrameElement ) {
		console.log("resizing")
		let contentWindow = iFrame.contentWindow
		if (contentWindow != null){
			iFrame.height = contentWindow.document.body.scrollHeight.toString();
		}
	}

</script>
<Scaffold>
	<Header slot="header" compact>{componentData.moduleName}</Header>
	<ContentContainer direction="column">
		<p class="subtitle">Contents</p>
		<ul>
			<li><Link href="#preview">Preview</Link></li>
			<li><Link href="#props">Props</Link></li>
			<li><Link href="#restprops">$$RestProps</Link></li>
			<li><Link href="#slots">Sls</Link></li>
			<li><Link href="#events">Events</Link></li>
		</ul>
		
		<p id="preview" class="subtitle">Preview</p>
		<iframe bind:this={iframe} src="/previews/{componentData.moduleName}" title="Preview for {componentData.moduleName}"></iframe>
		<Link arrow target="_blank" href="/previews/{componentData.moduleName}">Open preview in new tab</Link>
		<p id="props" class="subtitle">Props</p>
		<Table>
			<TableHeader>
				<TableCell isHeader>Name</TableCell>
				<TableCell isHeader>Description</TableCell>
				<TableCell isHeader>Type</TableCell>
				<TableCell isHeader>Required</TableCell>
				<TableCell isHeader>Reactive</TableCell>
				<TableCell isHeader>Default</TableCell>
			</TableHeader>
			{#each componentData.props as prop}
				<TableRow>
					<TableCell>{prop.name}</TableCell>
					{#if prop.description === undefined}
						<TableCell></TableCell>
					{:else}
						<TableCell>{prop.description}</TableCell>
					{/if}
					<TableCell><CodeBlock>{prop.type}</CodeBlock></TableCell>
					<TableCell>{prop.isRequired}</TableCell>
					<TableCell>{prop.reactive}</TableCell>
					{#if prop.value === undefined || prop.value === "\"\"" || prop.value === "''"}
						<TableCell></TableCell>
					{:else}
						<TableCell>{prop.value}</TableCell>
					{/if}
				</TableRow>
			{/each}
		</Table>
			
		{#if componentData.rest_props !=undefined}
			<p id="restprops" class="subtitle">$$restProps</p>
			<p>Applied on {componentData.rest_props.name}</p>
		{/if}
		<p id="slots" class="subtitle">Slots</p>
		{#each componentData.slots as slot}
			<p>
				{#if slot.default}
					Default
					<CodeBlock>default</CodeBlock>
				{:else}
					{slot.name}
				{/if}
			</p>
		{/each}
		<p id="events" class="subtitle">Events</p>
		{#each componentData.events as event}
			<p>
				{event.name}
				<CodeBlock>{event.type}</CodeBlock>
			</p>
		{/each}
		<p>Documentation generated by <Link href="https://github.com/carbon-design-system/sveld">sveld</Link></p>
	</ContentContainer>
</Scaffold>
<BackToTop></BackToTop>
<style>
	iframe {
		/* height: 30rem; */
		width:100%;
		border: var(--n300) solid 0.2rem;
		border-radius: var(--borderRadius);
		overflow: scroll;
		min-height: 15rem;
	}

	.subtitle {
		font:var(--subtitle);
	}

	p {
		font:var(--body);
	}

</style>